from __future__ import annotations

import re

# Absolute protocol caps. Deploy-time settings may lower these values, but they
# must never raise them without a reviewed contract/schema change.
ABSOLUTE_MAX_REQUEST_BODY_BYTES = 10 * 1024 * 1024
ABSOLUTE_MAX_CLOUD_BACKUP_PAYLOAD_BYTES = 8 * 1024 * 1024
ABSOLUTE_MAX_CLOUD_CHARACTER_PAYLOAD_BYTES = 4 * 1024 * 1024
ABSOLUTE_MAX_CHARACTER_MUTATION_PAYLOAD_BYTES = 512 * 1024
ABSOLUTE_MAX_CHARACTER_MUTATION_OPERATIONS = 128
ABSOLUTE_MAX_CHARACTER_MUTATION_PATH_LENGTH = 512
ABSOLUTE_MAX_CHARACTER_MUTATION_PATH_SEGMENTS = 32
ABSOLUTE_MAX_DEVICE_ID_LENGTH = 128
ABSOLUTE_MAX_SHARE_TARGET_LENGTH = 320
ABSOLUTE_MAX_REQUEST_ID_LENGTH = 128
ABSOLUTE_MAX_VALIDATION_ERRORS = 50
ABSOLUTE_MAX_AUDIT_USER_AGENT_LENGTH = 512
ABSOLUTE_MAX_LOG_FIELD_LENGTH = 4096
ABSOLUTE_MAX_CSRF_TOKEN_BYTES = 64
ABSOLUTE_MAX_CHARACTER_WRITE_RETRY_ATTEMPTS = 8
ABSOLUTE_MAX_CHARACTER_WRITE_RETRY_DELAY_MS = 5000
ABSOLUTE_MAX_SSE_RETRY_MILLISECONDS = 60_000
ABSOLUTE_MAX_SSE_STREAM_DURATION_SECONDS = 86_400
ABSOLUTE_MAX_SSE_TIMEOUT_SECONDS = 300
ABSOLUTE_MAX_SSE_SHUTDOWN_GRACE_SECONDS = 300
ABSOLUTE_MAX_DATA_RETENTION_DAYS = 3_650
ABSOLUTE_MAX_DATA_LIFECYCLE_BATCH_SIZE = 10_000
ABSOLUTE_MAX_CORS_PREFLIGHT_MAX_AGE_SECONDS = 86_400
ABSOLUTE_MAX_HSTS_MAX_AGE_SECONDS = 63_072_000
ABSOLUTE_MAX_SECURITY_HEADER_VALUE_LENGTH = 4_096
MAX_CHARACTER_SERVER_REVISION = 2_147_483_647
ABSOLUTE_MAX_JSON_DEPTH = 64
ABSOLUTE_MAX_JSON_STRING_LENGTH = 1024 * 1024

DEFAULT_MAX_REQUEST_BODY_BYTES = 6 * 1024 * 1024
DEFAULT_MAX_CLOUD_BACKUP_PAYLOAD_BYTES = 5 * 1024 * 1024
DEFAULT_MAX_CLOUD_CHARACTER_PAYLOAD_BYTES = 2 * 1024 * 1024
DEFAULT_MAX_CHARACTER_MUTATION_PAYLOAD_BYTES = 256 * 1024
DEFAULT_MAX_CHARACTER_MUTATION_OPERATIONS = 128
DEFAULT_MAX_CHARACTER_MUTATION_PATH_LENGTH = 512
DEFAULT_MAX_CHARACTER_MUTATION_PATH_SEGMENTS = 32
DEFAULT_MAX_DEVICE_ID_LENGTH = 128
DEFAULT_MAX_SHARE_TARGET_LENGTH = 320
DEFAULT_REQUEST_ID_HEADER_NAME = "X-Request-ID"
DEFAULT_REQUEST_ID_MAX_LENGTH = 96
DEFAULT_REQUEST_VALIDATION_MAX_ERRORS = 20
DEFAULT_MAX_JSON_DEPTH = 32
DEFAULT_MAX_JSON_STRING_LENGTH = 256 * 1024

API_ERROR_CODE_PATTERN = re.compile(r"^[A-Z][A-Z0-9_]{1,63}$")
HTTP_HEADER_NAME_PATTERN = re.compile(r"^[!#$%&'*+.^_`|~0-9A-Za-z-]+$")
# Deliberately conservative: request IDs may be supplied by a trusted proxy or
# frontend, but must remain one printable token with no delimiter ambiguity.
REQUEST_ID_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._:-]*$")


def require_valid_http_header_name(value: str, *, field_name: str) -> str:
    normalized = value.strip()
    if not normalized or HTTP_HEADER_NAME_PATTERN.fullmatch(normalized) is None:
        raise ValueError(f"{field_name} must be a valid HTTP header name")
    return normalized


def require_valid_api_error_code(value: str) -> str:
    normalized = value.strip()
    if API_ERROR_CODE_PATTERN.fullmatch(normalized) is None:
        raise ValueError(
            "API error code must use 2-64 uppercase ASCII letters, digits, or underscores"
        )
    return normalized


def is_valid_request_id(value: str, *, max_length: int) -> bool:
    return 1 <= len(value) <= max_length and REQUEST_ID_PATTERN.fullmatch(value) is not None
